// <auto-generated />
namespace Lisa.Civilization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Empty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Empty));
        
        string IMigrationMetadata.Id
        {
            get { return "201403110935002_Empty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
